// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVC.Data.Models
{
    public partial class Estado
    {
        public Estado()
        {
            Municipios = new HashSet<Municipio>();
        }

        public int Id { get; set; }
        public string Estado1 { get; set; }

        public virtual ICollection<Municipio> Municipios { get; set; }
    }
}